title: "Cristiano Fanelli"
description: "Astrofisico e Analista di Intelligence"

author:
  name: "Cristiano Fanelli"

social:
  name: "Cristiano Fanelli"
  links:
    - "https://github.com/CrisWat"
    - "https://www.linkedin.com/in/cristiano-fanelli-b881859a"

lang: "it-IT"
timezone: "Europe/Rome"

url: "https://www.fanellicristiano.it"
baseurl: ""

permalink: "/blog/:year/:month/:day/:title/"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - AGENTS.md
  - vendor
