name: "Cristiano Fanelli"
role_primary: "Astrofisico"
role_secondary: "Ricercatore INAF, Bologna"

linkedin: "https://www.linkedin.com/in/cristiano-fanelli-b881859a"
instagram: "https://www.instagram.com/cris_f91/"
github: "https://github.com/CrisWat"
unibo: "https://www.unibo.it/sitoweb/cristiano.fanelli3/"
inaf: "https://www.oas.inaf.it/en/user/cristiano.fanelli/"
futura: "https://futuramag.it/author/cristianofanelli/"
